import Cookies from "js-cookie";
import Head from "next/head";
import { useRouter } from "next/router";
import Services from "../components/Home/Services";
import Header from "../components/Home/Header";
import Nav from "../components/Home/Nav";
import Security from "../components/Home/Security";
import Web3 from "../components/Home/Web3";
import Features from "../components/Home/Features";

export default function Home() {
  const router = useRouter();
  const pKey = Cookies.get("publicKey");

  if (pKey) router.push("/wallet");

  return (
    <div>
      <Head>
        <title>
          CPay | Secure solana wallet making the world of web3 accessible to
          all.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav/>
      <Header/>
      <Services/>
      <Features/>
      <Security/>
      <Web3/>
    </div>
  );
}
